# Generated by Django 4.2.4 on 2023-09-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lapmake_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LapMake', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laptops_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputLapassetid', models.CharField(max_length=200, null=True)),
                ('inputLapSerialNo', models.CharField(max_length=200, null=True)),
                ('inputLapMake', models.CharField(max_length=200, null=True)),
                ('inputLapModel', models.CharField(max_length=200, null=True)),
                ('inputLapRAM', models.CharField(max_length=200, null=True)),
                ('inputLapHDD', models.CharField(max_length=200, null=True)),
                ('inputLapProcessor', models.CharField(max_length=200, null=True)),
                ('inputLappurchasedate', models.DateField(max_length=200, null=True)),
                ('inputLapuname', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laptops_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lapassetid', models.CharField(max_length=200, null=True)),
                ('LapSerialNo', models.CharField(max_length=200, null=True)),
                ('LapMake', models.CharField(max_length=200, null=True)),
                ('LapModel', models.CharField(max_length=200, null=True)),
                ('LapRAM', models.CharField(max_length=200, null=True)),
                ('LapHDD', models.CharField(max_length=200, null=True)),
                ('LapProcessor', models.CharField(max_length=200, null=True)),
                ('Lappurchasedate', models.DateField(default='', null=True)),
                ('Lapuname', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='location_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200, null=True)),
                ('location_name_val', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mobassetid', models.CharField(max_length=200, null=True)),
                ('MobSerialNo', models.CharField(max_length=200, null=True)),
                ('imei_number', models.CharField(max_length=200, null=True)),
                ('MobMake', models.CharField(max_length=200, null=True)),
                ('MobModel', models.CharField(max_length=200, null=True)),
                ('Mobpurchasedate', models.DateField(null=True)),
                ('Mobuname', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mobmake_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MobMake', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
