# Generated by Django 4.2.4 on 2023-09-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('processor', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255)),
                ('memory', models.FloatField()),
                ('disk_drive_model', models.CharField(max_length=255)),
                ('disk_drive_size', models.FloatField()),
                ('network_adapter_description', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=255)),
                ('computer_name', models.CharField(max_length=255)),
            ],
        ),
    ]
