# Generated by Django 4.2.4 on 2023-09-25 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_systeminfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemInfo',
        ),
    ]
