# Generated by Django 4.2.4 on 2023-08-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptops_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputLapassetid', models.CharField(max_length=200, null=True)),
                ('inputLapSerialNo', models.CharField(max_length=200, null=True)),
                ('inputLapMake', models.CharField(max_length=200, null=True)),
                ('inputLapModel', models.CharField(max_length=200, null=True)),
                ('inputLapRAM', models.CharField(max_length=200, null=True)),
                ('inputLapHDD', models.CharField(max_length=200, null=True)),
                ('inputLapProcessor', models.CharField(max_length=200, null=True)),
                ('inputLappurchasedate', models.DateField(max_length=200, null=True)),
                ('inputLapuname', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
