# Generated by Django 4.2.4 on 2023-08-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptops_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lapassetid', models.CharField(max_length=200, null=True)),
                ('LapSerialNo', models.CharField(max_length=200, null=True)),
                ('LapMake', models.CharField(max_length=200, null=True)),
                ('LapModel', models.CharField(max_length=200, null=True)),
                ('LapRAM', models.CharField(max_length=200, null=True)),
                ('LapHDD', models.CharField(max_length=200, null=True)),
                ('LapProcessor', models.CharField(max_length=200, null=True)),
                ('Lappurchasedate', models.DateField(max_length=200, null=True)),
                ('Lapuname', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
