# Generated by Django 4.2.4 on 2023-08-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_laptops_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptops_records',
            name='Lappurchasedate',
            field=models.DateField(default='', max_length=200, null=True),
        ),
    ]
