# Generated by Django 4.2.4 on 2023-08-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_laptops_records_lappurchasedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mobassetid', models.CharField(max_length=200, null=True)),
                ('MobSerialNo', models.CharField(max_length=200, null=True)),
                ('imei_number', models.CharField(max_length=200, null=True)),
                ('MobMake', models.CharField(max_length=200, null=True)),
                ('MobModel', models.CharField(max_length=200, null=True)),
                ('Mobpurchasedate', models.DateField(null=True)),
                ('Mobuname', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='laptops_records',
            name='Lappurchasedate',
            field=models.DateField(default='', null=True),
        ),
    ]
