# Generated by Django 4.2.4 on 2023-08-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_mobile_records_alter_laptops_records_lappurchasedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='location_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='make_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LapMake', models.CharField(max_length=200, null=True)),
                ('MobMake', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
