# Generated by Django 4.2.4 on 2023-08-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_location_details_make_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='make_details',
        ),
        migrations.AddField(
            model_name='location_details',
            name='location_name_val',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
