# Generated by Django 4.2.4 on 2023-08-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_delete_make_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lapmake_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LapMake', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mobmake_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MobMake', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
